### ISSUE TITLE
Cannot install bob.measure

### ISSUE THREAD

**Issue by omarcr** [bioidiap/bob.measure#13]
I have installed all the dependencies acording to the graph presented in https://github.com/idiap/bob/wiki/Dependencies:

However, I cannot isntall the pacakge this is the traceback:

```
omar@ubuntuv2:~/bob.measure$ sudo python setup.py 
Traceback (most recent call last):
  File "setup.py", line 50, in <module>
    boost_modules = boost_modules,
  File "/usr/local/lib/python2.7/dist-packages/bob/blitz/extension.py", line 52, in __init__
    BobExtension.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bob/extension/__init__.py", line 294, in __init__
    bob_includes, bob_libraries, bob_library_dirs, bob_macros = get_bob_libraries(self.bob_packages)
  File "/usr/local/lib/python2.7/dist-packages/bob/extension/__init__.py", line 186, in get_bob_libraries
    pkg = importlib.import_module(package)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/bob/math/__init__.py", line 6, in <module>
    bob.extension.load_bob_library('bob.math', __file__)
  File "/usr/local/lib/python2.7/dist-packages/bob/extension/__init__.py", line 237, in load_bob_library
    ctypes.cdll.LoadLibrary(full_libname)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python2.7/dist-packages/bob/math/libbob_math.so: undefined symbol: dsyevd_

```

**Comment by 183amir** [comment]
Have you tried our conda installation?

**Comment by omarcr** [comment]
OK I removed all bob packages then I did: 

```
$ sudo apt-get install python-software-properties #to install "add-apt-repository"
$ sudo add-apt-repository ppa:biometrics/bob #only the first time
$ sudo apt-get update #repeat this every time you need to update
$ sudo apt-get install bob 
```

It works now!
